name: zero_dynamics_policies
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python
  - "jaxlib=*=*cuda*"
  - jax
  - cuda-nvcc
  - cudnn
  - cython
  - scikit-learn
  - pandas
  - pip
  - scipy
  - matplotlib
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - jupyter
  - pytest
  - tf2onnx
  - datashader
  - libmujoco
  - mujoco
  - mujoco-mjx
  - mujoco-python
  - pip:
      - hydra-core
      - black
      - dill
      - isort
      - pytest
      - seaborn
      - flax
      - optax
      - diffrax
      - jaxlie
      - jaxopt
      - orbax-checkpoint
      - nvidia-pyindex
      - nvidia-tensorrt
      - wandb
      - pydantic
      - tqdm
      - pytest-pycharm
      - flashbax
      - perfetto
      - pyarrow
      - numdifftools
      - "tensorflow[and-cuda]"
      - cvxpylayers
